### ISSUE TITLE
Dependency on irobot_events_executor

### ISSUE THREAD

**Issue by ijnek** [ros-sports/hlvs_player#1]
Running rosdep fails with irobot_events_executor because it isn't released into ROS 2, with the following message:

```sh
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
hlvs_player: Cannot locate rosdep definition for [irobot_events_executor]
```

We should either:
* Ask iRobot to release https://github.com/irobot-ros/events-executor or
* Push harder for (and contribute to)  https://github.com/ros2/design/pull/305 or
* Use the normal executor from rclcpp

**Comment by SammyRamone** [comment]
I guess that iRobot does not really want to release it as an extra package as it would make more sens to finally integrate it into the normal rclcpp code base.
So I would say we should try to push finally merging the PRs of iRobot.

**Comment by ijnek** [comment]
I agree, these changes must be available when it comes to releasing this package. 
For now, for CI purposes, I'm going to add the irobot-ros/events_executor as a repository to build from source using action-ros-ci options in #4
