### ISSUE TITLE
Use environment variables for ip and port

### ISSUE THREAD

**Issue by Flova** [ros-sports/hlvs_player#7]
By default, the simulator IP and Port are passed into the docker container via an environment variable. This is described [here](http://humanoid.robocup.org/wp-content/uploads/v-hsc_server_specification_v1.03.pdf).
```
-eROBOCUP_SIMULATOR_ADDR=<Webots server IP>:<Player server port> \
```

In the current setup, teams need to create some glue code to convert this into ROS parameters. I would prefer a solution that works more out of the box. 

Any opinions?

**Comment by SammyRamone** [comment]
> By default, the simulator IP and Port are passed into the docker container via an environment variable. This is described [here](http://humanoid.robocup.org/wp-content/uploads/v-hsc_server_specification_v1.03.pdf).
> 
> ```
> -eROBOCUP_SIMULATOR_ADDR=<Webots server IP>:<Player server port> \
> ```
> 
> In the current setup, teams need to create some glue code to convert this into ROS parameters. I would prefer a solution that works more out of the box.
> 
> Any opinions?

good point!
Maybe just do a check if the ROS parameter is not set. In this case try to access the environment variable and if this also fails print an error?
